using System.Collections.Generic;
using System.Threading.Tasks;

namespace Theta_Bot.Database
{
    public interface IDataProvider
    {
        Task<Dictionary<string, bool>> GetCompletedLevelsAsync(string userId);
        Task SetLevelAsCompletedAsync(string userId, string levelId);

        Task<string> GetCurrentLevelAsync(string userId);
        Task SetCurrentLevelAsync(string userId, string levelId);

        Task<Exercise> GetCurrentExerciseAsync(string userId);
        Task SetCurrentExerciseAsync(string userId, Exercise exercise);

        Task<Dictionary<string, GeneratorState>> GetGeneratorStatesAsync(string userId);
        Task SetGeneratorStateAsync(string userId, string generatorId, GeneratorState state);

        Task<GeneratorHistory> GetGeneratorHistoryAsync(string generatorId);
        Task RaiseShowsCountAsync(string generatorsId);
        Task RaiseCorrectCountAsync(string generatorsId);
    }
    
    //userProgress
    //    <userId>
    //        completedLevels
    //            <levelId>: bool
    //        currentLevel
    //            levelId: string
    //            currentTask:
    //                taskId: id
    //                generatorId: string
    //                expectedAnswer: string
    //            generators
    //                <generatorId> 
    //                    correctAnswersCount: number
    //
    //generatorStats
    //    <generatorId>
    //        showsCount: number
    //        correctCount: number
    //        answers
    //            <autoGeneratedId>
    //                answer: string
    //                showsCount: number
    //                selectCount: number
    //                isCorrect: bool
}
