using System.Collections.Generic;
using System.Threading.Tasks;

namespace Theta_Bot.Database
{
    public interface IDataProvider
    {
        Task<Dictionary<string, bool>> GetCompletedLevels(string userId);
        Task SetLevelAsCompleted(string userId, string levelId);

        Task<string> GetCurrentLevel(string userId);
        Task SetCurrentLevel(string userId, string levelId);

        Task<Exercise> GetCurrentExercise(string userId);
        Task SetCurrentExercise(string userId, Exercise exercise);

        Task<Dictionary<string, GeneratorState>> GetGeneratorStates(string userId);
        Task SetGeneratorState(string userId, string generatorId, GeneratorState state);

        Task<GeneratorHistory> GetGeneratorHistory(string generatorId);
        Task RaiseShowsCount(string generatorsId);
        Task RaiseCorrectCount(string generatorsId);
    }
    
    //userProgress
    //    <userId>
    //        completedLevels
    //            <levelId>: bool
    //        currentLevel
    //            levelId: string
    //            currentTask:
    //                taskId: id
    //                generatorId: string
    //                expectedAnswer: string
    //            generators
    //                <generatorId> 
    //                    correctAnswersCount: number
    //generatorStats
    //    <generatorId>
    //        showsCount: number
    //        correctCount: number
    //        answers
    //            <autoGeneratedId>
    //                answer: string
    //                showsCount: number
    //                selectCount: number
    //                isCorrect: bool
}
